import Head from 'next/head'
import styles from '../styles/Home.module.css'

function Home ({ serverData }) {
  // console.log(serverData)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div>Hello, world!</div>
        {/* <div>{data[0].name}</div> */}
        <div>
          {serverData.map(d => (
            <div key={d.id}>{d.name}</div>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps () {
  // Fetch data from external API
  const res = await fetch(`https://jsonplaceholder.typicode.com/users`)
  const serverData = await res.json()

  // Pass data to the page via props
  return { props: { serverData } }
}

export default Home
